### PR TITLE
[CIVP-11405] Fix typo in setup.py

### PR DESCRIPTION
**Pull request by mikesaelim**

### CODE REVIEW

**Comment by keithing** [comment]
Good catch.  And tests still pass!  LGTM.

**Comment by mikesaelim** [comment]
But I haven't fixed anything yet...

**Comment by keithing** [comment]
Ah, I thought the PR was just to remove the travis `pip install requirements.txt`.  Please continue.

**Comment by mikesaelim** [comment]
@keithing Does this need anything else?  Version number change?

**Comment by keithing** [comment]
> Does this need anything else? Version number change?

We'll take care of version numbering in another PR.  But would you mind adding a line to CHANGELOG.md?  Under Unreleased, we'll need to add a new fixed header and then a short description that we fixed a setup.py bug.

**Pull request merged**
