### PR TITLE
Fixed/relaxed version specifications for click, jsonref, and jsonschema.

### LINKED ISSUE #376: Requirements incompatible with click v7.1
Pip has been giving me the following error: `ERROR: civis 1.12.1 has requirement click<=7,>=6.0, but you'll have click 7.1.1 which is incompatible.`. I would have thought that v7.1.1 is indeed <=7, but pip doesn't seem to agree. When I pip install civis-python from a fresh conda environment, pip gives me click v7.0.

I think the version restrictions should be relaxed to allow all `click` major version 7 or 6s.

### PR DESCRIPTION
**Pull request by mheilman**
Fixes #376

### CODE REVIEW

**Comment by mheilman** [comment]
To test this, I uninstalled click, ran `pip install -e .` to reinstall civis-python, and the latest version of click (7.1.1) was installed.

**Comment by jacksonllee** [comment]
Should we add `pip list` as the last step in the build, around and after [here](https://github.com/civisanalytics/civis-python/blob/9a777a553bfa0bead258a48e7cefa099c966f750/.travis.yml#L12)? That way, the build can tell us what's in a clean-slate environment for this sort of issues/bugs.

**Comment by mheilman** [comment]
@jacksonllee, travis already shows the versions of packages that get installed, if you expand the logs a bit (e.g., `Successfully installed cbor2-5.0.1 civis click-7.1.1 cloudpickle-1.3.0 importlib-metadata-1.5.0 jsonref-0.2 jsonschema-3.2.0 pubnub-4.5.0 pycryptodomex-3.9.7 pyrsistent-0.15.7 zipp-3.1.0` [here](https://travis-ci.com/github/civisanalytics/civis-python/jobs/298992361)). Does that satisfy your request for a `pip list`?

**Comment by jacksonllee** [comment]
> travis already shows the versions of packages that get installed, if you expand the logs a bit

Yeah I'm aware of that, though IMO it's not as nice as `pip list` or `pip freeze` as a final report. :-) Feel free to ignore my comment and merge this in.

**Pull request merged**
