### PR TITLE
Updates in prep for releasing 1.5.1

### PR DESCRIPTION
**Pull request by keithing**
This updates the changelog and version in preparation of releasing 1.5.1.

### CODE REVIEW

**Comment by keithing** [comment]
@stephen-hoover, I think we can get #83 in before we release.  I'll rebase after that merges.

**Comment by stephen-hoover** [comment]
@keithing , let me know when it's rebased and ready for a check.

**Comment by keithing** [comment]
@stephen-hoover, okay! This is ready now.

**Comment by stephen-hoover** [comment]
Ugh, I wrote that test too fragile. How about changing the assert to
```python
assert out == '{"job": 1, "run": 2}' or out == '{"run": 2, "job": 1}'
```
?

**Comment by keithing** [comment]
@stephen-hoover do you mind fixing that test in a separate PR?

**Comment by stephen-hoover** [comment]
#88 is merged. If you rebase, the tests should pass.

**Comment by keithing** [comment]
@stephen-hoover rebased and tests are now passing!

**Pull request merged**
