### PR TITLE
TST update test api specs

### PR DESCRIPTION
**Pull request by elsander**
This PR updates the API specs in the tests, including some feature-flagged endpoints.

### CODE REVIEW

**Comment by elsander** [comment]
Closing this PR in favor of opening a new one with a spec built from the robot user.

**Comment by stephen-hoover** [comment]
Just checking -- are the specs edited at all, aside from removing `channels` from `civis/tests/civis_api_spec.json`?

**Comment by elsander** [comment]
I removed all of the admin endpoints from both, otherwise no.

**Comment by elsander** [comment]
Ah, wait, there's a stray admin endpoint in the channels file, let me remove that first.

**Comment by elsander** [comment]
[deleted a comment that I had left in a stray admin endpoint-- I was looking at the wrong local branch. The merged branch doesn't have any admin endpoints]

**Pull request merged**
